### PR TITLE
 Fix generator for Palindrome Products

### LINKED ISSUE #715: Fix test generators
The following test generators are currently not working:
- [x] Allergies
- [ ] Palindrome (canonical data change [here](https://github.com/exercism/problem-specifications/commit/fbb30474df21e5de259493b010d5c502c049fa40#diff-11b95c88ab2f41a69599edd346658107))

### PR DESCRIPTION
**Pull request by davidelettieri**
Closes #715

### CODE REVIEW

File: exercises/palindrome-products/Example.fs [hunk 1]
```diff
@@ -11,7 +11,7 @@ let isPalindrome n =
 
 let palindrome predicate compare startValue minFactor maxFactor = 
     if minFactor > maxFactor then
-        None
+        failwith "min must be <= max"
```
Comment (ErikSchierboom) [inline exercises/palindrome-products/Example.fs]:
```suggestion
        invalidArg "min must be <= max"
```

As we are comparing parameters here, it is probably slightly more idiomatic to throw an `ArgumentException`, for which the `invalidArg` function can be used: https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/exception-handling/the-invalidarg-function

File: generators/Generators.fs [hunk 2]
```diff
@@ -871,20 +871,37 @@ type PalindromeProducts() =
...
             value.SelectToken("factors")
             |> List.mapRender toFactors
 
-        sprintf "(%d, %s)" palindromeValue factors
+        match palindromeValue with
+        | null -> sprintf "(None, %s)" factors
+        | _ -> sprintf "(Some %s, %s)" palindromeValue factors
+        
+    let isError (canonicalDataCase: CanonicalDataCase) =
+        match canonicalDataCase.Expected.Value("error") with
```
Comment (ErikSchierboom) [inline generators/Generators.fs]: Can this be:

```suggestion
        canonicalDataCase.Expected.Value("error") <> null
```

?

File: generators/Generators.fs [hunk 3]
```diff
@@ -871,20 +871,37 @@ type PalindromeProducts() =
...
     let toPalindromeProducts (value: JToken) =
-        let palindromeValue = value.Value<int>("value")
+        let palindromeValue = value.Value("value")
         let factors = 
             value.SelectToken("factors")
             |> List.mapRender toFactors
 
-        sprintf "(%d, %s)" palindromeValue factors
+        match palindromeValue with
+        | null -> sprintf "(None, %s)" factors
```
Comment (ErikSchierboom) [inline generators/Generators.fs]: I think you should be able to use the `Obj.render` function here.

File: generators/Generators.fs [hunk 4]
```diff
@@ -871,20 +871,37 @@ type PalindromeProducts() =
...
+        | _ -> sprintf "(Some %s, %s)" palindromeValue factors
```
Comment (ErikSchierboom) [inline generators/Generators.fs]: I think you should be able to use the `Obj.render` function here.

**Comment by davidelettieri** [comment]
Thanks for your review Erik! I'll take a look at it in a week or so.

**Comment by ErikSchierboom** [comment]
Sure! Take your time.

File: exercises/palindrome-products/Example.fs (hunk 1 above)
Comment (davidelettieri) [reply exercises/palindrome-products/Example.fs]: Sure, invalidArg wants the argument as first parameter it could be the tuple (min, max)

File: generators/Generators.fs (hunk 3 above)
Comment (davidelettieri) [reply generators/Generators.fs]: I think we can also go with "(None, [ ])" since it will be always like this in this case

File: generators/Generators.fs (hunk 4 above)
Comment (davidelettieri) [reply generators/Generators.fs]: I'll look into it, just applying the function to the tuple (palindromeValue, factors) does not produce a good result.

File: generators/Generators.fs (hunk 2 above)
Comment (davidelettieri) [reply generators/Generators.fs]: Sure, thanks!

File: generators/Generators.fs (hunk 3 above)
Comment (ErikSchierboom) [reply generators/Generators.fs]: Yeah, that would work!

File: generators/Generators.fs (hunk 4 above)
Comment (ErikSchierboom) [reply generators/Generators.fs]: Ah, if you don't get it working, then feel free to ignore!

Comment (davidelettieri) [reply generators/Generators.fs]: I didn't find a clean and easy way to use Obj.render

**Comment by ErikSchierboom** [comment]
LGTM! Thanks @davidelettieri
